[package]
name = "pdf-impose"
version.workspace = true
edition.workspace = true

[dependencies]
lopdf.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "sync", "rt"] }
