[package]
name = "pdf-flashcards"
version.workspace = true
edition.workspace = true

[dependencies]
printpdf = "0.8"
csv.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "sync", "rt"] }
